eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
  instance:
    hostname: localhost
server:
  port: 8082
spring:
  application:
    name: fare-management
  data:
    mongodb:
      uri: >-
        mongodb+srv://alfayeed:abcd1234@cluster0.8nm7y.mongodb.net/flight_booking_system
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flightauth
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
